"""Shared documents as agora-style nodes (ADR-0006)."""
import os
import subprocess
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from tests.test_xsm import TempState  # noqa: E402

AGENT = {"kind": "agent", "name": "w1", "alias": "claude-4", "ref": "aaaaaa"}
PERSON = {"kind": "human", "name": "me"}


class DocTest(TempState):
    def setUp(self):
        super().setUp()
        self.doc = os.path.join(self.tmp, "cache.md")

    def test_nodes_are_immutable_and_revisions_link_back(self):
        from xsm import doc
        a = doc.add(self.doc, AGENT, "redis is 2x faster", ["result"])
        b = doc.add(self.doc, AGENT, "redis is 2.1x faster (rerun)", ["result"], [a["id"]])
        self.assertEqual([n["id"] for n in doc.leaves(doc.read(self.doc))], [b["id"]])
        with self.assertRaises(doc.DocError):
            doc.add(self.doc, AGENT, "x", ["result"], ["nope"])

    def test_endorsed_is_a_persons_and_wins_the_render(self):
        from xsm import doc
        r = doc.add(self.doc, AGENT, "# Cache\\n\\nUse redis.", ["report"])
        with self.assertRaises(doc.DocError):
            doc.add(self.doc, AGENT, "# Cache", ["endorsed"], [r["id"]])
        doc.add(self.doc, AGENT, "# Cache v2\\n\\nUse redis, cluster mode.", ["report"])
        self.assertIn("cluster mode", doc.render(self.doc), "newest report without endorsement")
        doc.add(self.doc, PERSON, r["body"], ["endorsed"], [r["id"]])
        text = doc.render(self.doc)
        self.assertIn("generated by `xsm doc render`", text)
        self.assertIn("Use redis.", text)
        self.assertNotIn("cluster mode", text.split("## Open ends")[0])

    def test_unverified_hypotheses_are_listed(self):
        from xsm import doc
        h1 = doc.add(self.doc, AGENT, "LRU beats LFU here", ["hypothesis"])
        h2 = doc.add(self.doc, AGENT, "TTL of 60s is enough", ["hypothesis"])
        doc.add(self.doc, AGENT, "checked: TTL 60s holds", ["verification"], [h2["id"]])
        pending = [n["id"] for n in doc.unverified(doc.read(self.doc))]
        self.assertEqual(pending, [h1["id"]])
        self.assertIn("## Unverified hypotheses", doc.render(self.doc))

    def test_two_contributors_merge_without_conflict(self):
        """Each node is its own file, so two branches adding nodes merge cleanly."""
        from xsm import doc
        repo = os.path.join(self.tmp, "repo")
        os.makedirs(repo)
        run = lambda *a: subprocess.run(["git", "-C", repo] + list(a), check=True,
                                        capture_output=True)
        run("init", "-q")
        run("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-q", "--allow-empty", "-m", "0")
        d = os.path.join(repo, "notes.md")
        run("checkout", "-q", "-b", "a")
        doc.add(d, AGENT, "from a", ["result"])
        run("add", "-A"); run("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-q", "-m", "a")
        run("checkout", "-q", "-")
        run("checkout", "-q", "-b", "b")
        doc.add(d, AGENT, "from b", ["result"])
        run("add", "-A"); run("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-q", "-m", "b")
        run("-c", "user.email=t@t", "-c", "user.name=t", "merge", "-q", "--no-edit", "a")
        self.assertEqual(sorted(n["body"] for n in doc.read(d)), ["from a", "from b"])


if __name__ == "__main__":
    unittest.main()


class EndorseMcpTest(TempState):
    def test_endorse_asks_and_adds_a_persons_node(self):
        import io
        import json
        from xsm import doc, mcp
        path = os.path.join(self.tmp, "d.md")
        r = doc.add(path, AGENT, "the report", ["report"])
        msgs = [{"jsonrpc": "2.0", "id": 1, "method": "initialize",
                 "params": {"capabilities": {"elicitation": {}}}},
                {"jsonrpc": "2.0", "id": 2, "method": "tools/call", "params": {
                    "name": "xsm_doc_endorse", "arguments": {"doc": "d.md", "node": r["id"]}}},
                {"jsonrpc": "2.0", "id": "xsm-1",
                 "result": {"action": "accept", "content": {"answer": "endorse"}}}]
        out = io.StringIO()
        server = mcp.Server(io.StringIO("".join(json.dumps(m) + "\n" for m in msgs)), out)
        server.session = lambda: dict(AGENT, runtime="claude", cwd=self.tmp)
        server.serve()
        top = doc.canonical(doc.read(path))
        self.assertEqual((top["tags"], top["author_kind"], top["parents"]),
                         (["endorsed"], "human", [r["id"]]))
