"""Shared documents as agora-style nodes (ADR-0006).

A document `<path>.md` is written by nobody directly. Every contribution is an
immutable node in `<path>.md.nodes/<id>.md`, tagged and linked to the nodes it
builds on; the document itself is rendered from the nodes (`xsm doc render`).
So sessions never edit the same file: there is nothing to lock, nothing to
wait for, and a git merge of two contributors' nodes never conflicts, because
every node has its own name. Parallel work is all kept (agora, §3.2).

Nodes are never changed. To revise, add a node whose parent is the one it
revises. `endorsed` is a person's mark, like a channel decision: a person at a
terminal, or a session asking its user through MCP elicitation.
"""
from __future__ import annotations

import glob
import hashlib
import os
import time

TAGS = ("setup", "result", "insight", "hypothesis", "verification", "report", "wip", "endorsed")
GENERATED = "<!-- generated by `xsm doc render` from %s; do not edit: add a node instead -->"


class DocError(Exception):
    pass


def nodes_dir(doc: str) -> str:
    return os.path.realpath(os.path.expanduser(doc)) + ".nodes"


# --- one node --------------------------------------------------------------------

def _serialize(node: dict) -> str:
    head = ["---", "id: %s" % node["id"], "t: %s" % node["t"],
            "author: %s" % node["author"], "author_kind: %s" % node["author_kind"],
            "tags: %s" % ", ".join(node["tags"]), "parents: %s" % ", ".join(node["parents"])]
    if node.get("approved"):
        head.append("approved: %s" % node["approved"])
    return "\n".join(head + ["---", "", node["body"].rstrip(), ""])


def _parse(text: str) -> dict:
    if not text.startswith("---\n"):
        raise DocError("not a node")
    head, _, body = text[4:].partition("\n---\n")
    node = {"body": body.strip("\n")}
    for line in head.splitlines():
        key, _, value = line.partition(": ")
        node[key.strip()] = value.strip()
    node["tags"] = [t for t in node.get("tags", "").split(", ") if t]
    node["parents"] = [p for p in node.get("parents", "").split(", ") if p]
    return node


def read(doc: str) -> list:
    out = []
    for f in glob.glob(os.path.join(nodes_dir(doc), "*.md")):
        try:
            with open(f, encoding="utf-8") as fh:
                out.append(_parse(fh.read()))
        except (OSError, DocError):
            pass
    return sorted(out, key=lambda n: (n.get("t", ""), n.get("id", "")))


def add(doc: str, author: dict, body: str, tags: list, parents: list | None = None,
        approved: str | None = None) -> dict:
    body = (body or "").strip()
    if not body:
        raise DocError("a node needs a body")
    tags = [t for t in dict.fromkeys(tags or ["result"])]
    unknown = [t for t in tags if t not in TAGS]
    if unknown:
        raise DocError("unknown tag %s; tags: %s" % (", ".join(unknown), ", ".join(TAGS)))
    if "endorsed" in tags and author.get("kind") != "human":
        raise DocError("endorsing is a person's; from a session, ask your user with the "
                       "xsm_doc_endorse MCP tool")
    known = {n["id"] for n in read(doc)}
    missing = [p for p in (parents or []) if p not in known]
    if missing:
        raise DocError("no node %s in %s" % (", ".join(missing), doc))
    if author.get("kind") == "human":
        who = "%s (person%s)" % (author.get("name"), " via %s" % author["via"]
                                 if author.get("via") else "")
    else:
        who = "%s@%s [%s]" % (author.get("name"), author.get("alias"), author.get("ref"))
    node = {"t": time.strftime("%Y-%m-%dT%H:%M:%S%z"), "author": who,
            "author_kind": author.get("kind", "agent"), "tags": tags,
            "parents": list(parents or []), "body": body}
    if approved:
        node["approved"] = approved
    digest = hashlib.sha256(("%s|%s|%s|%s|%s" % (node["t"], who, ",".join(tags),
                                                 ",".join(node["parents"]), body)).encode())
    node["id"] = digest.hexdigest()[:12]
    os.makedirs(nodes_dir(doc), exist_ok=True)
    path = os.path.join(nodes_dir(doc), node["id"] + ".md")
    # O_EXCL: a node, once written, is never replaced.
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(_serialize(node))
    return node


# --- views (agora's analyze views, the ones a document needs) ------------------------

def children(nodes: list) -> dict:
    out = {}
    for n in nodes:
        for p in n["parents"]:
            out.setdefault(p, []).append(n)
    return out


def leaves(nodes: list) -> list:
    """Nodes nothing builds on yet: the open ends of the work."""
    kids = children(nodes)
    return [n for n in nodes if n["id"] not in kids]


def unverified(nodes: list) -> list:
    kids = children(nodes)
    return [n for n in nodes if "hypothesis" in n["tags"]
            and not any("verification" in k["tags"] for k in kids.get(n["id"], []))]


def canonical(nodes: list) -> dict | None:
    """The newest endorsed node, else the newest report."""
    for tag in ("endorsed", "report"):
        picked = [n for n in nodes if tag in n["tags"]]
        if picked:
            return picked[-1]
    return None


def _one_line(n: dict) -> str:
    first = (n["body"].strip().splitlines() or [""])[0][:90]
    return "- `%s` [%s] %s — %s" % (n["id"], ", ".join(n["tags"]), first, n["author"])


def render(doc: str) -> str:
    """Write the document from its nodes and return the text."""
    nodes = read(doc)
    rel = os.path.basename(nodes_dir(doc))
    out = [GENERATED % rel, ""]
    top = canonical(nodes)
    if top:
        out.append(top["body"].rstrip())
        out.append("")
        out.append("_From node `%s` (%s), %s._" % (top["id"], ", ".join(top["tags"]),
                                                  top["author"]))
    else:
        out.append("_No report yet. Add one with `xsm doc add %s --tag report`._"
                   % os.path.basename(doc))
    open_ends = [n for n in leaves(nodes) if not top or n["id"] != top["id"]]
    if open_ends:
        out += ["", "## Open ends", ""] + [_one_line(n) for n in open_ends]
    pending = unverified(nodes)
    if pending:
        out += ["", "## Unverified hypotheses", ""] + [_one_line(n) for n in pending]
    text = "\n".join(out).rstrip() + "\n"
    with open(os.path.realpath(os.path.expanduser(doc)), "w", encoding="utf-8") as fh:
        fh.write(text)
    return text


def log(nodes: list) -> str:
    return "\n".join("%s %s [%s] %s%s" % (n["id"], n["t"], ", ".join(n["tags"]), n["author"],
                                          " <- " + ", ".join(n["parents"]) if n["parents"] else "")
                     for n in nodes)


def wip_children(nodes: list) -> dict:
    """Parent id -> the `wip` nodes hanging off it. A `wip` node is a session
    saying out loud that it is working on something; it is a declaration, not a
    contribution, so it never becomes a candidate itself."""
    kids = children(nodes)
    return {pid: [k for k in ks if "wip" in k["tags"]] for pid, ks in kids.items()
            if any("wip" in k["tags"] for k in ks)}


def next_candidates(nodes: list) -> list:
    """What a session arriving at this document could pick up: the open ends
    and the hypotheses nobody has verified.

    Both sets already exist and `render()` already prints them in two sections;
    this view only puts them together, so no new judgement enters the document.
    **The order is the document's own** — `read()`'s, which is by timestamp and
    then by id, so nodes written in the same second fall in a stable but
    arbitrary order. It is not re-sorted here. No
    score, no ranking, no assignment: who picks what and on what signal is the
    open question of ADR-0012, and a ranking shipped here would settle it by
    accident."""
    picked, seen = [], set()
    candidates = {n["id"] for n in leaves(nodes)} | {n["id"] for n in unverified(nodes)}
    for n in nodes:
        if n["id"] in candidates and n["id"] not in seen and "wip" not in n["tags"]:
            seen.add(n["id"])
            picked.append(n)
    return picked


def _next_line(n: dict, wips: dict) -> str:
    why = []
    line = _one_line(n)
    held = wips.get(n["id"]) or []
    if held:
        # Said, not acted on: the node stays exactly where it is in the list.
        why.append("someone said they are on it (%s)" % ", ".join(k["author"] for k in held))
    return line + ("\n    " + "; ".join(why) if why else "")


def next_text(doc: str, limit: int = 0) -> str:
    nodes = read(doc)
    picked = next_candidates(nodes)
    if not picked:
        return "(nothing open: no loose ends and no unverified hypotheses)"
    wips = wip_children(nodes)
    shown = picked[:limit] if limit else picked
    out = [_next_line(n, wips) for n in shown]
    if len(shown) < len(picked):
        out.append("… and %d more" % (len(picked) - len(shown)))
    out.append("")
    out.append("In the document's own order, oldest first. xsm does not rank them and does not "
               "assign them; pick one and say so with `--tag wip --parent <id>`.")
    return "\n".join(out)


def next_json(doc: str, limit: int = 0) -> dict:
    nodes = read(doc)
    picked = next_candidates(nodes)
    wips = wip_children(nodes)
    ends = {n["id"] for n in leaves(nodes)}
    open_q = {n["id"] for n in unverified(nodes)}
    shown = picked[:limit] if limit else picked
    return {"doc": os.path.basename(doc),
            # Stated in the payload so a caller cannot mistake the list for a
            # ranking, and so a later version that does rank has to say so.
            "order": "created", "assigns": False, "total": len(picked),
            "candidates": [{"id": n["id"], "tags": n["tags"], "author": n["author"], "t": n["t"],
                            "why": [w for w in ("open end" if n["id"] in ends else "",
                                                "unverified hypothesis" if n["id"] in open_q
                                                else "") if w],
                            "wip": [k["author"] for k in wips.get(n["id"], [])]}
                           for n in shown]}
